version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    # command: bundle exec puma -C config/puma.rb -e production

    volumes:
      - .:/Im_here_docker
      - public-data:/Im_here_docker/public
      - tmp-data:/Im_here_docker/tmp
      - log-data:/Im_here_docker/log
    networks:
      - Im_here_docker-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: fitO2_development
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - Im_here_docker-network

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/Im_here_docker/public
      - tmp-data:/Im_here_docker/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - Im_here_docker-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  Im_here_docker-network:
    external: true
